Unit test dev
roahmlab/RAPTOR pull request #26
Opened 2024-09-15 02:03 UTC by Zichangzhou1234

modify scripts in /test fold in boost, add ctest in the cmakelist

2024-09-16 15:48 UTC, Cfather commented on .devcontainer/devcontainer.json
> +	"name": "RAPTOR-zichang",
You should not modify this file.

2024-09-16 15:51 UTC, Cfather requested changes

2024-09-16 15:51 UTC, Cfather commented on Examples/Kinova/SystemIdentification/ExcitingTrajectories/include/EndeffectorConditionNumberOptimizer.h
> +#ifndef CONDITION_NUMBER_OPTIMIZER_H
Please remove this since this is supposed to be in sys_id_dev. You should not develop different features in one branch.

2024-09-16 15:51 UTC, Cfather commented on Examples/Kinova/SystemIdentification/ExcitingTrajectories/src/EndEffectorConditionalNumberOptimizer.cpp
> +#include "EndeffectorConditionNumberOptimizer.h"
Please remove this since this is supposed to be in sys_id_dev. You should not develop different features in one branch.

2024-09-16 15:51 UTC, Cfather commented on Tests/KinematicsDynamics/TestRegressorInverseDynamics.cpp
> +
Please avoid adding unnecessary empty lines in your code. Keep things clean and organized.

2024-09-16 18:14 UTC, Zichangzhou1234 commented on Examples/Kinova/SystemIdentification/ExcitingTrajectories/KinovaRegressorExampleEndeffector.cpp
> +#include "EndeffectorConditionNumberOptimizer.h"
Can I just delete files and the create the pull request, but the log will exist

2024-09-16 19:16 UTC, Cfather commented on .devcontainer/devcontainer.json
> +	"name": "RAPTOR-zichang",
You should change the name locally. But don't push the change.

2024-10-04 17:07 UTC, Cfather approved these changes
Cleaned up a few things and fix KinematicsConstraints_test

2024-10-04 17:07 UTC, merged